name: Deploy Node Github Clone Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t whoshriyansh/github_clone_app_server:${{ github.sha }} .

      - name: Push Docker Image
        run: docker push whoshriyansh/github_clone_app_server:${{ github.sha }}

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker Image
        run: docker pull whoshriyansh/github_clone_app_server:${{ github.sha }}

      - name: Remove Old Container
        run: |
          docker stop nodejs-app-container || true
          docker rm nodejs-app-container || true

      - name: Run New Container
        run: |
          docker run -d \
            -p 4000:4000 \
            --name nodejs-app-container \
            -e MONGO_URI=${{ secrets.MONGO_URI }} \
            -e GIT_API_KEY=${{ secrets.GIT_API_KEY }} \
            -e GIT_CLIENT_ID=${{ secrets.GIT_CLIENT_ID }} \
            -e GIT_CLIENT_SECRET=${{ secrets.GIT_CLIENT_SECRET }} \
            whoshriyansh/github_clone_app_server:${{ github.sha }}
